### PR TITLE
Remove redundant phrase

### PR DESCRIPTION
**Pull request by pkq**
Remove the second occurrence of the phrase "an understanding of" from the summary.

### CODE REVIEW

**Comment by cbahlai** [comment]
Thanks for catching that! We got it in another round of edits that got uploaded with a bunch of other changes today!

**Comment by pkq** [comment]
Sure thing! BTW, really dig your OSRR course!

**Comment by cbahlai** [comment]
Thanks so much!!! Keep your eye on this space- I'm working on templating out the actual lesson plan pages over the next few days

**Comment by pkq** [comment]
Very cool, will do! :thumbsup:

**Pull request closed without merging**
